name: shmr_finance_app
description: "Finance app as first part of Yandex Summer School for mobile developers"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0
  flutter_svg: ^2.2.0
  flutter_bloc: ^9.1.1
  bloc_concurrency: ^0.3.0
  fuzzywuzzy: ^1.2.0
  drift: ^2.14.1
  sqlite3_flutter_libs: ^0.5.0
  path_provider: ^2.1.1
  path: ^1.8.3
  provider: ^6.1.1
  rxdart: ^0.27.7
  sensors_plus: ^6.1.1
  intl: ^0.20.2
  fl_chart: ^1.0.0

  uuid: ^4.5.1
  dio: ^5.8.0+1
  flutter_dotenv: ^5.2.1
  dio_smart_retry: ^7.0.1

  category_chart:
    path: packages/category_chart

dev_dependencies:
  flutter_test:
    sdk: flutter

  coca_lints: ^1.0.1
  build_runner: ^2.5.4
  freezed: ^3.0.6
  json_serializable: ^6.9.5
  drift_dev: ^2.14.1

  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.2.16

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/icon/
    - assets/splash/
    - .env

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"
  remove_alpha_ios: true

flutter_native_splash:
  color: "#ffffff"
  image: assets/splash/splash_image.png
  android_12:
    color: "#ffffff"
    image: assets/splash/splash_image.png
  android: true
  ios: true
  web: false
  fullscreen: true
  android_gravity: fill
  ios_content_mode: scaleToFill
