name: shmr_finance_app
description: "Finance app as first part of Yandex Summer School for mobile developers"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  coca_lints: ^1.0.0

flutter:
  uses-material-design: true
